Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jaja
// Descrição   : pede 2 numeros e da um resultado
// Autor(a)    : Guilherme
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
   area:real
   raio:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite o raio: ")
   leia(raio)

   area<-(pi)*(raio*raio)

   escreval("A area é: ", area)

Fimalgoritmo